name: bloc_communication_poc
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  feature_a:
    path:
      ./packages/feature_a
  feature_b:
    path:
      ./packages/feature_b
  feature_c:
    path:
      ./packages/feature_c
  bloc: ^8.1.0
